name: Issue assignment
on:
  issues:
    types: [opened]
jobs:
  auto-assing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assing issue'
        uses: pozil/auto-assing-issue@v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: alfonsod1986